# Generated by Django 4.1.5 on 2023-01-12 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countryModel',
            fields=[
                ('countryUuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=250)),
                ('capital', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
